### ISSUE TITLE
Sirens

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#10]
Hearing the siren's song will break down
[错误报告-2024-6-27_15.11.40.zip](https://github.com/user-attachments/files/16009551/-2024-6-27_15.11.40.zip)

**Comment by IAFEnvoy** [comment]
Same problem with #9

**Comment by IAFEnvoy** [comment]
以及下次别说break down了，break down是损坏的意思，应该用crash😂

**Comment by yuchen-guts** [comment]
I don't know English very well just translating with translation software, but I love this mod! Thank you very much for porting it over fabric!
