### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by egorpoka1** [ArkTechMC/IceAndFire-Fabric#12]
Hi, please can you tell me what mod is causing the incompatibility?
[crash-2024-06-27_22.42.25-server.txt](https://github.com/user-attachments/files/16020422/crash-2024-06-27_22.42.25-server.txt)

**Comment by egorpoka1** [comment]
in a single player game everything is fine

**Comment by yuchen-guts** [comment]
It's like the game screen freezes and doesn't generate any logs
