### ISSUE TITLE
Wearing equipment on the dragon will cause it to get stuck

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#13]
The game did not crash

**Comment by IAFEnvoy** [comment]
I want to know what the "stuck" mean. The dragon don't move? Or other phenomenon.

Also show me your game log.

**Comment by yuchen-guts** [comment]
The game screen is stuck and does not directly crash
I manually closed it, so there were no logs

**Comment by IAFEnvoy** [comment]
This bug has been reproduced. I will try to find the reason.
![Snipaste_2024-06-28_15-11-50](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/83523430/47f79424-358a-431e-9312-23f679eadc5a)
