### ISSUE TITLE
Dragon wearing armor won't get stuck, but it won't display completely

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#15]
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/ec583815-8cbb-4cbe-9e87-0cf94d89dcba)

**Comment by yuchen-guts** [comment]
Perhaps the texture update is too slow
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/21815cdc-540a-4f80-ac9a-84c839a9415f)

**Comment by IAFEnvoy** [comment]
Anyway, try this build first. I rewrite the armor render system yesterday.

https://github.com/ArkTechMC/IceAndFire-Fabric/actions/runs/9716077845/artifacts/1649434462

**Comment by IAFEnvoy** [comment]
还有就是要不要加一下qq群，GitHub上面聊着好累😩 966154502

**Comment by yuchen-guts** [comment]
哈哈
