### ISSUE TITLE
ocean

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#16]
I want to know if there are remnants of ice dragons that can be brushed on the sea
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/e88458c5-021d-4c34-8c30-d17fd6436490)

**Comment by yuchen-guts** [comment]
Can he possibly brush it

**Comment by yuchen-guts** [comment]
If the original mod generates ice dragon wreckage on the ocean, is that a bit too much

**Comment by yuchen-guts** [comment]
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/4ae0d1be-9df6-4295-972b-5ef691465d9f)

**Comment by IAFEnvoy** [comment]
I have found this lol. I'm discussing with my friends whether we need to remove it or keep it as a feature.

If you don't like it, you can try to override `iceandfire:structure_gen/ice` biome tag
