### ISSUE TITLE
The equipment of the Death Worm will become like this

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#18]
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/d7b66799-ab7b-4f0b-84f1-6d30b7e71ae7)
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/95eb6941-590d-4444-9d24-0d958d7ae3a4)

**Comment by IAFEnvoy** [comment]
Please provide your mod list. It seems that this is not a render problem simply caused by iaf

**Comment by yuchen-guts** [comment]
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/390d6c42-c652-4897-92c8-f8428ada8379)
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/6210fbf8-d16c-40d9-bc5d-cd209e74c75a)
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/134032988/1de3336b-8e1e-4ac3-be26-9c576fd40f21)
