### ISSUE TITLE
Crash related to pixie's?

### ISSUE THREAD

**Issue by withouthonor** [ArkTechMC/IceAndFire-Fabric#19]
Lady and I were playing, then crashed.  She was able to log back in and play fine for a few minutes, then when i logged back in my server immediately crashed again.  Appears it may be related to pixies?
[crash-2024-06-28_22.40.40-server.txt](https://github.com/user-attachments/files/16039861/crash-2024-06-28_22.40.40-server.txt)
[crash-2024-06-28_22.51.55-server.txt](https://github.com/user-attachments/files/16039863/crash-2024-06-28_22.51.55-server.txt)

**Comment by IAFEnvoy** [comment]
Another bug caused by calling client class on server. Maybe I need to make code review

**Comment by ImAK9** [comment]
Yeah, appears to not only be pixies but also other entities

**Comment by IAFEnvoy** [comment]
I have try to fix this issue. Try this file: https://github.com/ArkTechMC/IceAndFire-Fabric/actions/runs/9740750423/artifacts/1654480871

**Comment by ImAK9** [comment]
> I have try to fix this issue. Try this file: https://github.com/ArkTechMC/IceAndFire-Fabric/actions/runs/9740750423/artifacts/1654480871

Looks like it works
