### ISSUE TITLE
Gorgon Statues Are All Pigs

### ISSUE THREAD

**Issue by Nightfigure** [ArkTechMC/IceAndFire-Fabric#2]
Whenever the gorgon turns anything into a statue they become a pig
![Screenshot 2024-06-24 135739](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/138343710/26ee6781-1677-4165-ab9e-f6d56e495dec)

**Comment by IAFEnvoy** [comment]
Known issue from renderer. Will be fixed in next version.
