### ISSUE TITLE
crashes when i try to load a world with my modpack

### ISSUE THREAD

**Issue by GabanKillasta** [ArkTechMC/IceAndFire-Fabric#26]
i dont know why so ill just send my log and wait XD, it gets to 71% generated then crashes. my modpack is vanilla+ style, so if you want a copy i can send you a modlist or something so you can load it up as well and do some testing. hope to see this mod done soon as i LOVE it XD. good luck :)
[message (1).txt](https://github.com/user-attachments/files/16240504/message.1.txt)

**Comment by IAFEnvoy** [comment]
It seems that you set the value of `cyclops.spawnCaveChance` in config to non-positive number
