### ISSUE TITLE
Server crashing when loading dragon entities

### ISSUE THREAD

**Issue by Chubbo5** [ArkTechMC/IceAndFire-Fabric#28]
I run a Ploxhost server for me and my friends and I just recently added this mod to the pack we usually use. Whenever a player loads a dragon skeleton (From what I am guessing from the crash report) the server crashes. I don't know why this is happening. I will add the crash report and mod list below.

[crash-2024-07-22_01.35.49-server.txt](https://github.com/user-attachments/files/16419971/crash-2024-07-22_01.35.49-server.txt)

[Mods.txt](https://github.com/user-attachments/files/16420036/Mods.txt)

**Comment by IAFEnvoy** [comment]
It seems that valkyrienskies miss a native library and this error have no relation with iaf.
Also there is no iaf in the crash report mod list.

**Comment by Chubbo5** [comment]
I'm sorry, I gave you the wrong crash report, this should be the right one. Again sorry.

[crash-2024-07-30_04.10.28-server.txt](https://github.com/user-attachments/files/16421913/crash-2024-07-30_04.10.28-server.txt)

**Comment by Chubbo5** [comment]
I found the issue!

Turns out that the C2me mod doesn't like the idea of dragon dens and dragon skeletons spawning in the world.

**Comment by IAFEnvoy** [comment]
c2me have conflicted for a long time
