### ISSUE TITLE
Grogon's freezing is sometimes REALLY laggy

### ISSUE THREAD

**Issue by LordEnder-Kitty** [ArkTechMC/IceAndFire-Fabric#29]
I don't have a screenshot of what happened, but twice while fighting a gorgon, i got turned to stone, and it caused severe server lag. In the logs it said this "Can't keep up! Is the server overloaded? Running 36929ms or 738 ticks behind" which I'm pretty sure isn't very good. I don't know if that's a my computer thing or if it's the mod, but i got frozen another time and i was fine. What happens when it lags like that is the stone statue appears and the gorgon stop attacking, however, i'm still there and can move around. armor pieces just randomly broke every few seconds, and then after, like, 30 seconds, it catches up and kills me.

**Comment by IAFEnvoy** [comment]
please provide logs
