### ISSUE TITLE
Crashes server on load

### ISSUE THREAD

**Issue by ImAK9** [ArkTechMC/IceAndFire-Fabric#3]
**Mod Version:** 0.1
**FAPI Version:** 0.92.2

### Links
[Stacktrace of Crash](https://hastebin.skyra.pw/datebukayu.pgsql)
[Full Log](https://hastebin.skyra.pw/vijufelexu.nestedtext)

Seems like perhaps you're trying to load client classes on the server?

**Comment by IAFEnvoy** [comment]
I know this issue. Wait for future update since the mod is still in beta.

I will notify you later.
