### ISSUE TITLE
Async entity load when server tried to load dragon skeleton or dragon on fabric port

### ISSUE THREAD

**Issue by gedaun** [ArkTechMC/IceAndFire-Fabric#30]
### What had happened?
crashed and cannot connect with error getsockopt

*What you have done and what happen*
loaded dragon skeleton or dragon
### Mod Version (Include dependencies)
0.4
~~x.y.z~~

### Mod Loader Version

~~Fabric 0.16.0~~

### Game Log

https://mclo.gs/dXyoeKY

### Checklist

- [yes] I don't install Optifine
- [yes] I have installed other mods

**Comment by IAFEnvoy** [comment]
This is a conflict with c2me and fixed in 0.5
