### ISSUE TITLE
Lag all over the map

### ISSUE THREAD

**Issue by Nicksolo99** [ArkTechMC/IceAndFire-Fabric#32]
### What had happened?

I have a modpack, that includes terraforming mods, I'm not using distant horizons or similar, I used to play with +30 chunks view, as soon as I installed Ice and Fire mod, it works great, but it added a terrible lag as if I was playing in an online server, but I'm playing alone
I added 20Gbs to that modpack, and it never goes beyond 11Gbs, I don't get what's causing such an overload

### Mod Version (Include dependencies)

~~0.6 alpha5~~

### Mod Loader Version

~~Fabric 1.20.1~~

### Game Log

Game log added, I know it may include many other mods, but I have tried everything, deleting other mods, and so on but the issue persists
[Game log.txt](https://github.com/user-attachments/files/16631925/Game.log.txt)

### Checklist

- [X] I don't install Optifine
- [X] I have installed other mods

**Comment by Nicksolo99** [comment]
Extra comment, just tried removing the mod and the issue goes away, sad I wanted to try that mod after so many years, I know you're not the official developer and you're doing a great job, but I don't know why it gets overloaded in my modpack.
Will wait for future updates in the mod whenever you launch a non-beta or alpha version

**Comment by IAFEnvoy** [comment]
I need some information about your laggy world. Use Spark Mod and export the report.
