### ISSUE TITLE
[Bug/Incompatibility] Mob icons break on JourneyMap

### ISSUE THREAD

**Issue by NFLD99** [ArkTechMC/IceAndFire-Fabric#37]
### What had happened?
view a iceand fire mob on JourneyMap

### Mod Version (Include dependencies)
[iceandfire-0.5.1.jar](https://www.curseforge.com/minecraft/mc-mods/iceandfire-fabric/files/5588915)
[Uranus-1.6.1.jar](https://www.curseforge.com/minecraft/mc-mods/uranus/files/5600816)
[Jupiter-0.5-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/jupiter/files/5627086)

### Mod Loader Version
Fabric 0.16.0

### Game Log
[latest - Server](https://gist.githubusercontent.com/NFLD99/29b2ff0795eba28ae1fd1b7125813164/raw/fd5e71fa3d84a7d97b825d1efe6b2ee969b781b0/latest%20-%20Server.log)
[latest - Client](https://gist.githubusercontent.com/NFLD99/c53c1741499647bf67ec6684b1da4be2/raw/85143d6333948099cd4f9059e5b8891ec469215e/latest%20-%20Client.log)

### Checklist
- [❌] I don't install Optifine
- [✔] I have installed other mods

### Modpack
[Fluffcraft 1.1.33](https://www.curseforge.com/minecraft/modpacks/fluffcraft/files/5676047)

**Comment by IAFEnvoy** [comment]
`[11:38:39] [JM-task-6/INFO]: If Sodium is installed you must also install Indium. Otherwise another mod is breaking support`

Install Indium

**Comment by NFLD99** [comment]
> `[11:38:39] [JM-task-6/INFO]: If Sodium is installed you must also install Indium. Otherwise another mod is breaking support`
> 
> Install Indium

Indium is installed, issue persists.

**Comment by NFLD99** [comment]
i also made a fresh instance with only the below mods, same issue 
Fabric API
IceAndFire Fabric
JourneyMap
Jupiter
Uranus

https://github.com/user-attachments/assets/338c75a3-5e80-42dc-87b7-ee903c8f9a66

**Comment by NFLD99** [comment]
according to https://teamjm.github.io/journeymap-docs/latest/Tools%20and%20Customisation/custom-mob-icons/ it may be due to the textures being in `\textures\models` not `\textures\entity` with a `\textures\entity_icon`

**Comment by IAFEnvoy** [comment]
Not wrong path. There are no `entity_icon` specific yet. This kind of resouorce also not exist in the forge version.

**Comment by NFLD99** [comment]
talked to the JM devs, they pushed an update to allow retexturing it, im making a janky RP until the mod has it officially
