### ISSUE TITLE
Invisible Dragon Projectiles when Using Shaders

### ISSUE THREAD

**Issue by ValerieOwO** [ArkTechMC/IceAndFire-Fabric#40]
Dragon breath projectiles are invisible when using shaders. I'm using Iris, playing on 1.20.1 with the latest mod version.

**Comment by IAFEnvoy** [comment]
Which shader you are using?

**Comment by ValerieOwO** [comment]
I'm using Complementary Shaders Reimagined.

**Comment by IAFEnvoy** [comment]
Try to disable `IPBR Particle Features` in shader settings
