### ISSUE TITLE
no items have tags

### ISSUE THREAD

**Issue by closed-captions** [ArkTechMC/IceAndFire-Fabric#41]
### What had happened?

says it all in the title. i was running a modpack with Almost Unified and noticed that the silver from this mod wasn't merged with the silvers from other mods

### Mod Version (Include dependencies)

Ice & Fire 0.6
Uranus 1.6.1
Jupiter 1.0

### Mod Loader Version

Quilt 0.26.3

### Game Log

(might not be necessary for this exact issue? do let me know if it is needed)

### Checklist

- [x] I don't install Optifine
- [x] I have installed other mods

**Comment by IAFEnvoy** [comment]
i use the legacy tags just someone tell me. You can modify it through datapack manually before i update this.

**Comment by IAFEnvoy** [comment]
Asked fabric developers, my tags name don't have issues. You can change it using datapack.

![image](https://github.com/user-attachments/assets/0b550a47-2d62-4bb6-ba42-0504bf9f5057)

Don't ask me to compat with Quilt. I never use it.
