### ISSUE TITLE
[Bug] Fire Dragons Spawn On Nether Roof

### ISSUE THREAD

**Issue by NFLD99** [ArkTechMC/IceAndFire-Fabric#42]
### What had happened?
Fire Dragons spawn on top of the nether roof

### Mod Version (Include dependencies)
[[1.20.1] Fabric API 0.92.2+1.20.1](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/5383715)
[iceandfire-0.6.jar](https://www.curseforge.com/minecraft/mc-mods/iceandfire-fabric/files/5686370)
[Jupiter-1.0-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/jupiter/files/5685082)
[Uranus-1.6.1.jar](https://www.curseforge.com/minecraft/mc-mods/uranus/files/5600816)

### Mod Loader Version
Fabric 0.16.3

### Game Log
[latest.log](https://github.com/user-attachments/files/16861747/latest.log)

### Checklist
- [✔] I don't install Optifine
- [❌] I have installed other mods

### Screenshots
![2024-09-04_03 54 28](https://github.com/user-attachments/assets/a2ba9466-ae74-4218-9034-075b87ee4852)
![2024-09-04_03 53 52](https://github.com/user-attachments/assets/0dbcc002-a8f1-4024-92e2-c7af214ca1f9)
* Both taken on the same world, Seed: -2012744511100024327

**Comment by IAFEnvoy** [comment]
We have found it before and keep it as a feature.

You can remove it with datapack if you don't like it.
