### ISSUE TITLE
Mobs and creature from ice and fire spawning in wrong biome.

### ISSUE THREAD

**Issue by AlphaXc-N** [ArkTechMC/IceAndFire-Fabric#43]
Ok now i have to talk. I started my IAF Fabric edition from java 1.20.1 mod v0.6-alpha6 (fabric loader 0.16.2). Since than im finding some creatures that spawn in the wrong biomes.

First of all lightning dragon . all dragon are fine except lightning dragon , they are spawning everywhere meaning almost every biome . the . The lightning dragon fossil , cave and even aboveground roasts. it seems to like they are spawning more in the ochen . actually most of the time in the ochen biomes and river (i have founded them in cold ochen , river, frozen ochen, frozen river ) . the aboveground nest spawned in a frozen ochen (maybe there was some block to support it ). 

then the desert marmix . they are spawning in beaches . i have founded 3 of them 

the pixies are also spawning everywhere . meaning absolute every where like its cow or sheep . and they are annoying. 

and very last amphithere , they are spawning wayy far from jungle eventually in plains . 200 blocks far from jungle . 

so fix them really quick , cause they may cause sum serious issues. And thanks to fix dragon bow infinite issues !  
Mod Version  0.6-alpha6 to 0.6 the recent one

**Comment by IAFEnvoy** [comment]
1. Where is the issue template?
2. Have you update mod to latest version?
3. Have you even read README?
