### ISSUE TITLE
Dragon Corpse Can Only be Looted by Right-Clicking Dragon Part Instead of Body

### ISSUE THREAD

**Issue by plante3** [ArkTechMC/IceAndFire-Fabric#46]
Dragon corpses cannot be looted by right-clicking the corpse's center. Instead one has to right-click one of the many 
dragon part entities, which is the opposite of original Ice and Fire behavior.

![image](https://github.com/user-attachments/assets/e4b97e9c-4729-4889-8166-8952df886cb1)

### Mod Version (Include dependencies)

Ice and Fire Fabric 0.6.1
Uranus 1.7
Jupiter 1.0

### Mod Loader Version

Fabric Loader 0.16.5 on Minecraft 1.20.1

### Checklist

- [X] I don't install Optifine
- [ ] I have installed other mods

**Comment by IAFEnvoy** [comment]
You need to right click with an empty hand.
