### ISSUE TITLE
There Is No Third-Person Camera Perspective for Riding Dragons Keybind

### ISSUE THREAD

**Issue by plante3** [ArkTechMC/IceAndFire-Fabric#47]
Since Ice and Fire 1.5.1 there has been a hotkey (F7 by default) to change the third-person camera perspective when riding a dragon. This is not present in the keybinds menu.

![image](https://github.com/user-attachments/assets/3b5918de-3dab-41a6-a804-6758d76374cc)

### Mod Version (Include dependencies)
Ice and Fire Fabric 0.6.1
Uranus 1.7
Jupiter 1.0

### Mod Loader Version

Fabric Loader 0.16.5 on Minecraft 1.20.1

### Checklist

- [X] I don't install Optifine
- [ ] I have installed other mods

**Comment by IAFEnvoy** [comment]
F5?
