### ISSUE TITLE
Gorgon destroys armor with keep inventory

### ISSUE THREAD

**Issue by ThePoultryMan** [ArkTechMC/IceAndFire-Fabric#48]
### What had happened?

When the keepInventory gamerule is set to true, all armor that the player is wearing is destroyed if they are turned to stone.

### Mod Version (Include dependencies)

Ice and Fire Fabric: 0.6.1
Uranus: 1.7
Jupiter: 1.0

EMI: 1.1.13+1.20.1+fabric

### Mod Loader Version

Fabric 0.16.5

### Game Log

I only have client logs, I don't have access to server logs.

[Client Logs (mclo.gs)](https://mclo.gs/cwell6j)

### Checklist

- [x] I don't install Optifine
- [x] I have installed other mods

### Additional Information

This was reported in the forge version in [#3669](https://github.com/AlexModGuy/Ice_and_Fire/issues/3669)

**Comment by IAFEnvoy** [comment]
This bug also exists in forge version lol.

**Comment by ThePoultryMan** [comment]
Could it still be fixed? Existing in the forge version doesn't seem like a good reason to not fix a bug. I'm willing to create a pr to fix it, if it's not something being intentionally left in.

**Comment by IAFEnvoy** [comment]
nonono, fixed
