### ISSUE TITLE
ice and fire 

### ISSUE THREAD

**Issue by Antics96** [ArkTechMC/IceAndFire-Fabric#53]
### What had happened? dragons states 

*What you have done and what happen* cant see what age a dragon is 

### Mod Version (Include dependencies) 1.20.1

~~x.y.z~~

### Mod Loader Version 1.20.1

~~Fabric 0.16.0~~

### Game Log

*Recommended to upload it onto mclo.gs, pastebin and so on.*

### Checklist

- [ ] I don't install Optifine
- [ ] I have installed other mods

**Comment by IAFEnvoy** [comment]
**PLEASE DESCRIBE IN MORE DETAILS AND PROVIDE AT LEAST MOD&DEPENDENCIES INFORMATION OR I WILL PERMANENTLY BLOCK YOUR ISSUES.**

**Comment by IAFEnvoy** [comment]
you mean ride on it?

also you need to wait for uploading image, or it will not display

**Comment by Antics96** [comment]
no i mean when you open a dragons menu to put a saddle on.

![image](https://github.com/user-attachments/assets/a33e2eb4-ede4-48f9-b00e-db76e70b7237)

**Comment by IAFEnvoy** [comment]
if you installed `carry on` just restart game.

this is caused when you carry on this dragon then put it off

**Comment by IAFEnvoy** [comment]
iaf have conflict with `carry on`, if you carry a dragon it will cause this
