### ISSUE TITLE
Troll weapons dont render

### ISSUE THREAD

**Issue by Nightfigure** [ArkTechMC/IceAndFire-Fabric#6]
![image](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/138343710/f446d2a0-a7f7-4b73-a828-f22483364b25)

**Comment by IAFEnvoy** [comment]
I fix it just 1 hours ago lol. (Push was later)

**Comment by IAFEnvoy** [comment]
This will fix in 0.1.2
