### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shinycolororange** [ArkTechMC/IceAndFire-Fabric#61]
### What had happened?

start game

### Mod Version (Include dependencies)

uranus 2.0
fire and ice 7.1
juptier 2.0

### Mod Loader Version

Fabric 0.16.9

### Game Log

https://mclo.gs/PTHjLrm

### Checklist

- [yes ] I don't install Optifine
- [ yes] I have installed other mods

**Comment by IAFEnvoy** [comment]
Do not use latest version of Uranus
