### ISSUE TITLE
Mouse over ogre armor crashes.

### ISSUE THREAD

**Issue by yuchen-guts** [ArkTechMC/IceAndFire-Fabric#8]
[crash-2024-06-27_02.27.10-client.txt](https://github.com/user-attachments/files/15993787/crash-2024-06-27_02.27.10-client.txt)
[latest.log](https://github.com/user-attachments/files/15993789/latest.log)

**Comment by yuchen-guts** [comment]
[crash-2024-06-27_02.27.10-client.txt](https://github.com/user-attachments/files/15993792/crash-2024-06-27_02.27.10-client.txt)

**Comment by IAFEnvoy** [comment]
This crash caused by ArmorTip mod, not the problem of this mod.

**Comment by yuchen-guts** [comment]
ok
